import { ReactNode } from "react";

import type { Metadata } from "next";
import "./globals.css";

import { getAuthenticatedAppForUser } from "@/lib/firebase/serverApp";

import Header from "@/components/header/header";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const { currentUser } = await getAuthenticatedAppForUser();

  return (
    <html lang="en">
      <body>
        <Header initialUser={currentUser} />
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
