import type { Metadata } from "next";
import "./globals.css";
import { getAuthenticatedAppForUser } from "@/lib/firebase/serverApp";
import Header from "@/components/header/header";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const { currentUser } = await getAuthenticatedAppForUser();

  return (
    <html lang="en">
      <body>
        <Header initialUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
